POST http://localhost:3333/api/links
Content-Type: application/json

{
  "code": "pedro",
  "url": "https://pedro-dias.vercel.app/"
}

###

GET http://localhost:3333/api/links

###

GET http://localhost:3333/api/metrics

###

GET http://localhost:3333/pedro

